application: assist-incorelabs 
version: 1
runtime: php55
api_version: 1

handlers:

- url: /(.*\.(ico$|jpg$|png$|gif$))
  static_files: \1
  upload: (.*\.(ico$|jpg$|png$|gif$))
  application_readable: true

- url: /(.*\.(htm$|html$|css$|js$))
  static_files: \1
  upload: (.*\.(htm$|html$|css$|js$))
  application_readable: true

- url: /
  script: index.php

- url: /contacts
  script: /contacts/index.php
